In [ ]:
import nltk
import re
import numpy
from nltk.corpus import stopwords

In [ ]:
def word_extraction(sentence):
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in stopwords.words('english')]
    return cleaned_text

<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:2: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_777/2040892463.py:2: SyntaxWarning: invalid escape sequence '\w'
  words = re.sub("[^\w]", " ",  sentence).split()


In [ ]:
def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)
    words = sorted(list(set(words)))
    return words

In [ ]:
# S1 = ['it','was','the','best','of']
# S2 = ['i','love','python','so','much']
# S3 = ['he','was','playing','the','game']

# words = ['it','was','the','best','of','i','love','python','so','much','he','was','playing','the','game']
# words = [['it','was','the','best','of'] , ['i','love','python','so','much'] , ['he','was','playing','the','game']]



In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
text = "Mary and Samantha arrived at the bus station early but waited until noon for the bus"

In [ ]:
word_extraction(text)

['mary',
 'samantha',
 'arrived',
 'bus',
 'station',
 'early',
 'waited',
 'noon',
 'bus']

2 bus bus

In [ ]:
len(word_extraction(text))

9

In [ ]:
tokenize(word_extraction(text))

['arrived', 'bus', 'early', 'mary', 'noon', 'samantha', 'station', 'waited']

In [ ]:
len(tokenize(word_extraction(text)))

8

In [ ]:
def generate_bow(allsentences):
    vocab = tokenize(allsentences)
    print("Word List for Document \n{0} \n".format(vocab))
    for sentence in allsentences:
        words = word_extraction(sentence)
        bag_vector = numpy.zeros(len(vocab))
        for w in words:
            for i,word in enumerate(vocab):
                if word == w:
                    bag_vector[i] += 1
        print("{0}\n{1}\n".format(sentence,numpy.array(bag_vector)))
        print('---------------------------------------------------')

In [ ]:
generate_bow(word_extraction(text))

Word List for Document 
['arrived', 'bus', 'early', 'mary', 'noon', 'samantha', 'station', 'waited'] 

mary
[0. 0. 0. 1. 0. 0. 0. 0.]

---------------------------------------------------
samantha
[0. 0. 0. 0. 0. 1. 0. 0.]

---------------------------------------------------
arrived
[1. 0. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
bus
[0. 1. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
station
[0. 0. 0. 0. 0. 0. 1. 0.]

---------------------------------------------------
early
[0. 0. 1. 0. 0. 0. 0. 0.]

---------------------------------------------------
waited
[0. 0. 0. 0. 0. 0. 0. 1.]

---------------------------------------------------
noon
[0. 0. 0. 0. 1. 0. 0. 0.]

---------------------------------------------------
bus
[0. 1. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------


In [ ]:
allsentences = ["Joe waited for the train",
                "The train was late",
                "Mary and Samantha took the bus",
               "I looked for Mary and Samantha at the bus station",
                "Mary and Samantha arrived at the bus station early but waited until noon for the bus"]

In [ ]:
generate_bow(allsentences)

Word List for Document 
['arrived', 'bus', 'early', 'i', 'joe', 'late', 'looked', 'mary', 'noon', 'samantha', 'station', 'the', 'took', 'train', 'waited'] 

Joe waited for the train
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]

---------------------------------------------------
The train was late
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]

---------------------------------------------------
Mary and Samantha took the bus
[0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0.]

---------------------------------------------------
I looked for Mary and Samantha at the bus station
[0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0.]

---------------------------------------------------
Mary and Samantha arrived at the bus station early but waited until noon for the bus
[1. 2. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1.]

---------------------------------------------------


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(allsentences)
print(X.toarray()[1])
for i in range(len(allsentences)) :
    print(allsentences[i])
    print(X.toarray()[i])

    print('---------------------------------------------------')

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1]
Joe waited for the train
[0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 0]
---------------------------------------------------
The train was late
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1]
---------------------------------------------------
Mary and Samantha took the bus
[1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0]
---------------------------------------------------
I looked for Mary and Samantha at the bus station
[1 0 1 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0]
---------------------------------------------------
Mary and Samantha arrived at the bus station early but waited until noon for the bus
[1 1 1 2 1 1 1 0 0 0 1 1 1 1 2 0 0 1 1 0]
---------------------------------------------------


In [ ]:
text = "ذهب محمد و شريف الي المدرسة هذا اليوم"

In [ ]:
word_extraction(text)

['ذهب', 'محمد', 'و', 'شريف', 'الي', 'المدرسة', 'هذا', 'اليوم']

In [ ]:
tokenize(word_extraction(text))

['المدرسة', 'الي', 'اليوم', 'ذهب', 'شريف', 'محمد', 'هذا', 'و']

In [ ]:
generate_bow(word_extraction(text))

Word List for Document 
['المدرسة', 'الي', 'اليوم', 'ذهب', 'شريف', 'محمد', 'هذا', 'و'] 

ذهب
[0. 0. 0. 1. 0. 0. 0. 0.]

---------------------------------------------------
محمد
[0. 0. 0. 0. 0. 1. 0. 0.]

---------------------------------------------------
و
[0. 0. 0. 0. 0. 0. 0. 1.]

---------------------------------------------------
شريف
[0. 0. 0. 0. 1. 0. 0. 0.]

---------------------------------------------------
الي
[0. 1. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
المدرسة
[1. 0. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
هذا
[0. 0. 0. 0. 0. 0. 1. 0.]

---------------------------------------------------
اليوم
[0. 0. 1. 0. 0. 0. 0. 0.]

---------------------------------------------------


In [ ]:
allsentences = ["ذهب محمد الي الجامعة",
                "نجحت مني في الاختبار",
                "تمكن محمد من السفر هذا اليوم",
               "اعتقد ان جورج سيتصل بنا اليوم",
                "لا اظن ان الاختبار سيكون سهلا"]

In [ ]:
generate_bow(allsentences)

Word List for Document 
['اظن', 'اعتقد', 'الاختبار', 'الجامعة', 'السفر', 'الي', 'اليوم', 'ان', 'بنا', 'تمكن', 'جورج', 'ذهب', 'سهلا', 'سيتصل', 'سيكون', 'في', 'لا', 'محمد', 'من', 'مني', 'نجحت', 'هذا'] 

ذهب محمد الي الجامعة
[0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

---------------------------------------------------
نجحت مني في الاختبار
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.]

---------------------------------------------------
تمكن محمد من السفر هذا اليوم
[0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]

---------------------------------------------------
اعتقد ان جورج سيتصل بنا اليوم
[0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
لا اظن ان الاختبار سيكون سهلا
[1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0.]

---------------------------------------------------


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(allsentences)

for i in range(len(allsentences)) :
    print(allsentences[i])
    print(list(X.toarray()[i]))
    print('---------------------------------------------------')

ذهب محمد الي الجامعة
[np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0)]
---------------------------------------------------
نجحت مني في الاختبار
[np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(0)]
---------------------------------------------------
تمكن محمد من السفر هذا اليوم
[np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.