In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head(30)

,Article
0,"In the Washington of 2016, even when the polic..."
1,Donald Trump has used Twitter — his prefe...
2,Donald Trump is unabashedly praising Russian...
3,"Updated at 2:50 p. m. ET, Russian President Vl..."
4,"From photography, illustration and video, to d..."
5,I did not want to join yoga class. I hated tho...
6,With a who has publicly supported the debunk...
7,"I was standing by the airport exit, debating w..."
8,"If movies were trying to be more realistic, pe..."
9,"Eighteen years ago, on New Year’s Eve, David F..."


In [7]:
npr.shape

(11992, 1)

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = cv.fit_transform(npr['Article'])

In [19]:
len(cv.get_feature_names_out())

54777

In [17]:
top=cv.get_feature_names_out().argmax()
print(cv.get_feature_names_out()[top])

überfunky


In [8]:
cv.vocabulary_

{'washington': 53112,
 '2016': 436,
 'policy': 37382,
 'bipartisan': 5867,
 'politics': 37411,
 'sense': 43740,
 'year': 54403,
 'shows': 44460,
 'little': 28875,
 'sign': 44648,
 'ending': 16578,
 'dec': 12950,
 '31': 604,
 'president': 38079,
 'obama': 34145,
 'moved': 32459,
 'sanction': 42732,
 'russia': 42390,
 'alleged': 2437,
 'interference': 25508,
 'election': 16123,
 'just': 26752,
 'concluded': 10646,
 'republicans': 41011,
 'long': 29070,
 'called': 7832,
 'similar': 44724,
 'severe': 43916,
 'measures': 30766,
 'scarcely': 43060,
 'bring': 7061,
 'approve': 3373,
 'house': 23698,
 'speaker': 45934,
 'paul': 36007,
 'ryan': 42428,
 'appropriate': 3364,
 'overdue': 35153,
 'prime': 38202,
 'example': 17430,
 'administration': 1762,
 'ineffective': 24926,
 'foreign': 19398,
 'left': 28266,
 'america': 2689,
 'weaker': 53234,
 'eyes': 17881,
 'world': 54102,
 'gop': 21161,
 'leaders': 28148,
 'sounded': 45783,
 'theme': 49105,
 'urging': 51889,
 'years': 54412,
 'strong': 4716

In [6]:
dtm.shape

(11992, 54777)

In [10]:
import random
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names_out()[random_word_id])

courtesan
bivens
choate
orfield
steen
honoring
postdoc
dehaan
facilitated
mortifying


In [67]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
documents = [
    "football team goal match coach",
    "basketball player score game",
    "government election president vote",
    "minister parliament politics law",
    "python machine learning neural network",
    "deep learning tensorflow pytorch",
    "football stadium striker coach",
    "AI transformer language model"
]
vectorizer = CountVectorizer(stop_words="english")

X = vectorizer.fit_transform(documents)
lda = LatentDirichletAllocation(
    n_components=3,
    random_state=42
)
results=lda.fit_transform(X)
print(lda.components_.shape)
# print(lda.components_)
feature_names = vectorizer.get_feature_names_out()

for topic_idx, topic in enumerate(lda.components_):
    print(f"Topic {topic_idx}")

    top_words = topic.argsort()[::-1][:5]

    print(feature_names[top_words])
for i,prob in enumerate(results):
    print(i,">>>>",prob)
most=results.argmax(axis=1)
df=pd.DataFrame(most,columns=['topic'])
print(df)

(3, 31)
Topic 0
['transformer' 'language' 'model' 'ai' 'learning']
Topic 1
['learning' 'president' 'vote' 'government' 'election']
Topic 2
['coach' 'football' 'team' 'goal' 'match']
0 >>>> [0.05618217 0.05594385 0.88787398]
1 >>>> [0.0676328  0.06726589 0.86510131]
2 >>>> [0.06741917 0.86555012 0.06703071]
3 >>>> [0.06741917 0.86555012 0.06703071]
4 >>>> [0.05635363 0.05826245 0.88538392]
5 >>>> [0.06741565 0.86362167 0.06896268]
6 >>>> [0.06737111 0.06710439 0.8655245 ]
7 >>>> [0.86614522 0.06695931 0.06689547]
   topic
0      2
1      2
2      1
3      1
4      2
5      1
6      2
7      0


In [47]:
from sklearn.decomposition import LatentDirichletAllocation
LDA = LatentDirichletAllocation(n_components=7,random_state=42)
LDA.fit_transform(dtm)

array([[1.61040465e-02, 6.83341493e-01, 2.25376318e-04, ...,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04],
       [3.63424997e-02, 8.86130697e-01, 4.40751747e-04, ...,
        7.57636804e-02, 4.40866779e-04, 4.40835574e-04],
       [3.28569485e-04, 6.96344889e-01, 3.28302105e-04, ...,
        3.02012902e-01, 3.28724083e-04, 3.28352652e-04],
       ...,
       [1.44467964e-02, 1.60696622e-01, 1.73678310e-01, ...,
        2.24636569e-02, 3.98728349e-04, 3.98359730e-04],
       [4.33560738e-04, 3.53196803e-02, 4.33022554e-04, ...,
        9.62512640e-01, 4.33971991e-04, 4.33490254e-04],
       [3.98777533e-01, 2.54376049e-04, 3.59290659e-01, ...,
        2.40914375e-01, 2.54445555e-04, 2.54253739e-04]])

In [48]:
LDA.components_.shape

(7, 54777)

In [49]:
len(LDA.components_)

7

In [24]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [25]:
len(LDA.components_) , len(LDA.components_[0])

(7, 54777)

In [26]:
single_topic = LDA.components_[0]
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [ ]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [ ]:
for index in single_topic.argsort()[-10:]:
    print(cv.get_feature_names_out()[index])

new
percent
government
company
million
care
people
health
said
says


In [32]:
import spacy

nlp = spacy.load("en_core_web_sm")

for index, topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #{index+1}")

    words = [cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]]

    doc = nlp(" ".join(words))

    print(", ".join(
        token.lemma_.lower()
        for token in doc
        if token.is_alpha
    ))

    print()

THE TOP 15 WORDS FOR TOPIC #1
company, money, year, federal, new, percent, government, company, million, care, people, health, say, say

THE TOP 15 WORDS FOR TOPIC #2
military, house, security, russia, government, npr, report, say, news, people, tell, police, president, trump, say

THE TOP 15 WORDS FOR TOPIC #3
way, world, family, home, day, time, water, city, new, year, food, just, people, like, say

THE TOP 15 WORDS FOR TOPIC #4
time, new, don, year, medical, disease, patient, just, child, study, like, woman, health, people, say

THE TOP 15 WORDS FOR TOPIC #5
voter, vote, election, party, new, obama, court, republican, campaign, people, state, president, clinton, say, trump

THE TOP 15 WORDS FOR TOPIC #6
year, go, ve, life, don, new, way, music, really, time, know, think, people, just, like

THE TOP 15 WORDS FOR TOPIC #7
student, year, datum, science, university, people, time, school, just, education, new, like, student, school, say



In [53]:
topic_results = LDA.transform(dtm)

In [34]:
topic_results.shape

(11992, 7)

In [35]:
LDA.components_.shape

(7, 54777)

array([42993, 42561, 42993, 42993, 50426, 28659, 42993])

In [36]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [43]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0])

In [44]:
set(topic_results.argmax(axis=1))

{np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6)}

In [38]:
npr['Topic'] = topic_results.argmax(axis=1)
npr.head(10)

,Article,Topic
0,"In the Washington of 2016, even when the polic...",1
1,Donald Trump has used Twitter — his prefe...,1
2,Donald Trump is unabashedly praising Russian...,1
3,"Updated at 2:50 p. m. ET, Russian President Vl...",1
4,"From photography, illustration and video, to d...",2
5,I did not want to join yoga class. I hated tho...,3
6,With a who has publicly supported the debunk...,3
7,"I was standing by the airport exit, debating w...",2
8,"If movies were trying to be more realistic, pe...",3
9,"Eighteen years ago, on New Year’s Eve, David F...",2
